name: Build and publish On-Prem Agent

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'entrypoint.sh'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/onprem_agent
  DOCKERHUB_IMAGE_NAME: singularbyte/pixelbar-onprem-agent

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ${{ env.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            latest

      - name: Build Docker image for scanning
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: temp-image-for-scan
          cache-from: |
            type=gha
            type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:cache
            type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:latest

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: temp-image-for-scan
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:cache
            type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:latest
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.DOCKERHUB_IMAGE_NAME }}:cache,mode=max

 